
include $(SIMSCRIPTS_DIR)/mkfiles/plusargs.mk

TIMEOUT := 100us

MK_INCLUDES += $(ROCKET_SOC)/ve/rocket_soc_uvm/sim/scripts/rocket_soc_uvm.mk

TB=rocket_soc_subsys_tb
TB_MODULES=RocketSocTB RocketSocTBHvl rocket_soc_subsys_tests_pkg

include $(SIMSCRIPTS_DIR)/mkfiles/common_sim.mk


	
