#ifndef INCLUDED_ROCKET_SOC_MEMMAP_H
#define INCLUDED_ROCKET_SOC_MEMMAP_H

#define ROCKET_SOC_PERIPH_BASE (void *)0x60000000

#define ROCKET_SOC_UART0_BASE (void *)(ROCKET_SOC_PERIPH_BASE + 0)


#endif /* INCLUDED_ROCKET_SOC_MEMMAP_H */
